name: VehicleWorkshop

services:
   app:
      build:
         context: ..
         dockerfile: ./docker/Dockerfile
         target: prod
      restart: unless-stopped
      ports:
         - "80:80"
         - "443:443"
      environment:
         DB_HOST: postgres
         DB_PORT: "5432"
         DB_NAME: ${POSTGRES_DB:?POSTGRES_DB not in .env}
         DB_USER: ${POSTGRES_USER:?POSTGRES_USER not in .env}
         DB_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not in .env}
         CACHE_HOST: valkey
         CACHE_PORT: "6379"
         CACHE_PASSWORD: ${VALKEY_PASSWORD:?VALKEY_PASSWORD not in .env}
      depends_on:
         postgres:
            condition: service_healthy
         valkey:
            condition: service_healthy
      networks:
         - app_net
         - data_net

   postgres:
      image: postgres:16.14-alpine3.24@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777
      restart: unless-stopped
      environment:
         POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER not in .env}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not in .env}
         POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB not in .env}
      volumes:
         - postgres_data:/var/lib/postgresql/data
      healthcheck:
         test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:?POSTGRES_USER not in .env} -d ${POSTGRES_DB:?POSTGRES_DB not in .env}" ]
         interval: 5s
         timeout: 5s
         retries: 5
      networks:
         - data_net

   valkey:
      image: valkey/valkey:9.1.1-alpine3.24@sha256:ee91f7a174ac4d6a6b0685b3a60e321f0a9dbbb691f9b0e285be2ba1d1be8328
      restart: unless-stopped
      environment:
         VALKEY_EXTRA_FLAGS: --requirepass ${VALKEY_PASSWORD:?VALKEY_PASSWORD not in .env}
      volumes:
         - valkey_data:/data
      healthcheck:
         test: [ "CMD-SHELL", "valkey-cli -a ${VALKEY_PASSWORD:?VALKEY_PASSWORD not in .env} ping | grep -q PONG" ]
         interval: 5s
         timeout: 5s
         retries: 5
      networks:
         - data_net

networks:
   app_net:
      driver: bridge
   data_net:
      driver: bridge

volumes:
   postgres_data:
   valkey_data:
